name: humble

on: [push, pull_request]

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: humble, ROS_REPO: main}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          path: src/zlac_ros2

      - name: serial
        uses: actions/checkout@v4
        with:
          repository: clone https://github.com/joshnewans/serial.git
          path: src/serial

      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
      